version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
